---
# tasks file for docker
- name: Prepare Host for Docker Install
  include: install_prereqs.yml
  become: yes

- name: Install Docker
  include: install_docker.yml
  become: yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
    checksum: "{{ docker_compose_checksum }}"
  when: docker_compose_install | bool
  become: yes

- name: Configure Docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
    lstrip_blocks: yes
    trim_blocks: yes
  become: yes
  notify: restart docker

- name: Configure Swarm
  include: configure_swarm.yml
  become: yes

- name: Install ContainX Netshare
  include: containx_netshare.yml
  when: docker_containx_netshare_install | bool
  become: yes